language: node_js
before_install:
  - "npm install -g eslint"
script:
  - "eslint ."
  - "node unittest-runner.js"
services:
- redis-server
cache:
  directories:
    - node_modules
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false
deploy:
  provider: heroku
  app: lokki
  on:
    repo: TheSoftwareFactory/lokki-server
  api_key:
    secure: gWWnIwTXbjjWbhp1+n58WoTyD8kSpNyt9QCN/3VVnjtFN8Pdan2Jtc95CCawg0LR6URC71qXc/eRUeDgHnkptYstnEnVzLkC9yHuKidLswuQuiwVgJreivFRZAxw7PibCxmgLYpGSkIpT4VOG4lTSiVPBL9Y+rhBNlc9WfXxz0w=
